### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by hughperkins** [benbogin/obverter#2]
Hi Ben, thank you very much for creating this replication of Ed Choi's paper. Extremely useful :) Don't suppose... could it be possible to add a license to the repo, so that I can adapt the code for my own works, potentially? For example, the MIT license is very nice, https://github.com/git/git-scm.com/blob/main/MIT-LICENSE.txt .

**Comment by benbogin** [comment]
Hi, thanks!
Sure no problem, I'll add the MIT license.

**Comment by hughperkins** [comment]
Awesome! Thank you :)
